"""empty message

Revision ID: ab738f06b73f
Revises: e6f9da210004
Create Date: 2020-06-09 17:40:15.819466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab738f06b73f'
down_revision = 'e6f9da210004'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('d_cotrimoxazole', sa.Float(), nullable=True))
    op.add_column('patient', sa.Column('d_daunorubicin', sa.Float(), nullable=True))
    op.add_column('patient', sa.Column('d_ecoli', sa.Float(), nullable=True))
    op.add_column('patient', sa.Column('d_methotrexate', sa.Float(), nullable=True))
    op.add_column('patient', sa.Column('d_pegaspargase', sa.Float(), nullable=True))
    op.add_column('patient', sa.Column('d_prednisolone', sa.Float(), nullable=True))
    op.add_column('patient', sa.Column('d_vincristine', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient', 'd_vincristine')
    op.drop_column('patient', 'd_prednisolone')
    op.drop_column('patient', 'd_pegaspargase')
    op.drop_column('patient', 'd_methotrexate')
    op.drop_column('patient', 'd_ecoli')
    op.drop_column('patient', 'd_daunorubicin')
    op.drop_column('patient', 'd_cotrimoxazole')
    # ### end Alembic commands ###
