"""empty message

Revision ID: e6f9da210004
Revises: e774edf77662
Create Date: 2020-06-06 17:49:31.623941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6f9da210004'
down_revision = 'e774edf77662'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_risk_factor_patient_age', table_name='risk_factor')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_risk_factor_patient_age', 'risk_factor', ['patient_age'], unique=False)
    # ### end Alembic commands ###
