"""risk factors table

Revision ID: e774edf77662
Revises: 66ac9c4e97de
Create Date: 2020-06-06 17:47:04.069128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e774edf77662'
down_revision = '66ac9c4e97de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_risk_factor_patient_age'), 'risk_factor', ['patient_age'], unique=False)
    op.drop_constraint(None, 'risk_factor', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'risk_factor', 'patient', ['patient_age'], ['age'])
    op.drop_index(op.f('ix_risk_factor_patient_age'), table_name='risk_factor')
    # ### end Alembic commands ###
